"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Players",
      [
        {
          nba_id: 200746,
          display_name: "LaMarcus Aldridge",
          player_code: "lamarcus_aldridge",
          off_rating: 119,
          def_rating: 112,
          ast_per_100: 1.9,
          two_pt_attempts: 412,
          two_pt_makes: 238,
          three_pt_attempts: 46,
          three_pt_makes: 14,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/200746.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1627761,
          display_name: "DeAndre' Bembry",
          player_code: "deandre'_bembry",
          off_rating: 120,
          def_rating: 111,
          ast_per_100: 3.1,
          two_pt_attempts: 177,
          two_pt_makes: 106,
          three_pt_attempts: 36,
          three_pt_makes: 15,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1627761.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1628971,
          display_name: "Bruce Brown",
          player_code: "bruce_brown",
          off_rating: 121,
          def_rating: 111,
          ast_per_100: 4.0,
          two_pt_attempts: 412,
          two_pt_makes: 218,
          three_pt_attempts: 94,
          three_pt_makes: 38,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1628971.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1628975,
          display_name: "Jevon Carter",
          player_code: "jevon_carter",
          off_rating: 94,
          def_rating: 115,
          ast_per_100: 4.0,
          two_pt_attempts: 47,
          two_pt_makes: 16,
          three_pt_attempts: 127,
          three_pt_makes: 42,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1628975.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1629651,
          display_name: "Nic Claxton",
          player_code: "nicolas_claxton",
          off_rating: 130,
          def_rating: 111,
          ast_per_100: 2.1,
          two_pt_attempts: 264,
          two_pt_makes: 178,
          three_pt_attempts: 0,
          three_pt_makes: 0,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1629651.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 203552,
          display_name: "Seth Curry",
          player_code: "seth_curry",
          off_rating: 121,
          def_rating: 116,
          ast_per_100: 4.2,
          two_pt_attempts: 87,
          two_pt_makes: 46,
          three_pt_attempts: 124,
          three_pt_makes: 58,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203552.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201609,
          display_name: "Goran Dragic",
          player_code: "goran_dragic",
          off_rating: 98,
          def_rating: 115,
          ast_per_100: 9.1,
          two_pt_attempts: 68,
          two_pt_makes: 32,
          three_pt_attempts: 49,
          three_pt_makes: 12,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201609.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 203083,
          display_name: "Andre Drummond",
          player_code: "andre_drummond",
          off_rating: 121,
          def_rating: 106,
          ast_per_100: 3.1,
          two_pt_attempts: 194,
          two_pt_makes: 119,
          three_pt_attempts: 1,
          three_pt_makes: 0,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203083.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1630561,
          display_name: "David Duke Jr.",
          player_code: "david_duke_jr",
          off_rating: 104,
          def_rating: 113,
          ast_per_100: 2.4,
          two_pt_attempts: 71,
          two_pt_makes: 30,
          three_pt_attempts: 37,
          three_pt_makes: 9,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1630561.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201142,
          display_name: "Kevin Durant",
          player_code: "kevin_durant",
          off_rating: 121,
          def_rating: 112,
          ast_per_100: 8.3,
          two_pt_attempts: 815,
          two_pt_makes: 463,
          three_pt_attempts: 300,
          three_pt_makes: 115,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1630556,
          display_name: "Kessler Edwards",
          player_code: "kessler_edwards",
          off_rating: 100,
          def_rating: 113,
          ast_per_100: 1.5,
          two_pt_attempts: 131,
          two_pt_makes: 62,
          three_pt_attempts: 136,
          three_pt_makes: 48,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1630556.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201933,
          display_name: "Blake Griffin",
          player_code: "blake_griffin",
          off_rating: 115,
          def_rating: 113,
          ast_per_100: 5.3,
          two_pt_attempts: 168,
          two_pt_makes: 95,
          three_pt_attempts: 145,
          three_pt_makes: 38,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201933.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201935,
          display_name: "James Harden",
          player_code: "james_harden",
          off_rating: 112,
          def_rating: 111,
          ast_per_100: 13.3,
          two_pt_attempts: 399,
          two_pt_makes: 190,
          three_pt_attempts: 307,
          three_pt_makes: 102,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201935.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 203925,
          display_name: "Joe Harris",
          player_code: "joe_harris",
          off_rating: 112,
          def_rating: 116,
          ast_per_100: 1.6,
          two_pt_attempts: 36,
          two_pt_makes: 15,
          three_pt_attempts: 88,
          three_pt_makes: 41,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203925.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 202681,
          display_name: "Kyrie Irving",
          player_code: "kyrie_irving",
          off_rating: 117,
          def_rating: 114,
          ast_per_100: 7.4,
          two_pt_attempts: 377,
          two_pt_makes: 189,
          three_pt_attempts: 239,
          three_pt_makes: 100,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/202681.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201949,
          display_name: "James Johnson",
          player_code: "james_johnson",
          off_rating: 109,
          def_rating: 113,
          ast_per_100: 5.3,
          two_pt_attempts: 222,
          two_pt_makes: 121,
          three_pt_attempts: 85,
          three_pt_makes: 23,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201949.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 201988,
          display_name: "Patty Mills",
          player_code: "patty_mills",
          off_rating: 112,
          def_rating: 117,
          ast_per_100: 3.8,
          two_pt_attempts: 226,
          two_pt_makes: 97,
          three_pt_attempts: 568,
          three_pt_makes: 227,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201988.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 200794,
          display_name: "Paul Millsap",
          player_code: "paul_millsap",
          off_rating: 105,
          def_rating: 110,
          ast_per_100: 4.3,
          two_pt_attempts: 58,
          two_pt_makes: 26,
          three_pt_attempts: 27,
          three_pt_makes: 6,
          image: "https://cdn.nba.com/headshots/nba/latest/1040x760/200794.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1630549,
          display_name: "Day'Ron Sharpe",
          player_code: "dayron_sharpe",
          off_rating: 118,
          def_rating: 111,
          ast_per_100: 2.1,
          two_pt_attempts: 142,
          two_pt_makes: 84,
          three_pt_attempts: 7,
          three_pt_makes: 2,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1630549.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          nba_id: 1630560,
          display_name: "Cam Thomas",
          player_code: "cam_thomas",
          off_rating: 103,
          def_rating: 115,
          ast_per_100: 3.2,
          two_pt_attempts: 329,
          two_pt_makes: 171,
          three_pt_attempts: 174,
          three_pt_makes: 47,
          image:
            "https://cdn.nba.com/headshots/nba/latest/1040x760/1630560.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Players", null, {});
  },
};
